# Generated by Django 4.2 on 2023-04-14 10:06

from django.db import migrations, models
import phonenumber_field.modelfields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=32, null=True, region=None, unique=True, verbose_name='Phone number')),
                ('full_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Full name')),
                ('position', models.CharField(max_length=50)),
                ('avatar', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users/%Y/%m/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('date_of_employment', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('type', models.CharField(choices=[('Staff', 'Staff'), ('Intern', 'Intern')], default='Staff', max_length=20, verbose_name='Staff type')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
    ]
