# Generated by Django 4.2 on 2023-04-14 10:06

import ckeditor.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='Time From')),
                ('end_time', models.DateTimeField(verbose_name='Time To')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='events/%Y/%m', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
