# Generated by Django 4.2 on 2023-04-14 16:50

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='events/%Y/%m', verbose_name='Image'),
        ),
    ]
