# Generated by Django 4.2 on 2023-04-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='work_start_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lateness_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Lateness time'),
        ),
    ]
